Feature/get detalle publicacion
nachogg18/bibliotech pull request #106
Opened 2023-10-12 04:35 UTC by juanrojas216

2023-10-12 04:37 UTC, juanrojas216 commented
Devuelve 
```
public class DetallePublicacionDTO {
    private Long id;
    private String tituloPublicacion;
    private String isbnPublicacion;
    private Integer nroPaginas;
    private Integer anioPblicacion;
    private List<AutorDTO> autores = new ArrayList<>();
    private Edicion edicion;
    private List<Editorial> editoriales = new ArrayList<>();
    private List<DetalleCategoriaDTO> categorias = new ArrayList<>();
    private Link link;
}
```

2023-10-12 06:02 UTC, nachogg18 commented on src/main/java/com/bibliotech/controller/PublicacionController.java
che si sacas esto se rompe el by params jajaj, 

fijate esto

```
.autores(
                        (Objects.nonNull(publicacion.getAutores()))
                            ? publicacion.getAutores().stream()
```
Objects.nonNull(publicacion.getAutores()) checkea que no sea null

2023-10-12 06:03 UTC, nachogg18 requested changes

2023-10-12 06:03 UTC, nachogg18 commented on src/main/java/com/bibliotech/controller/PublicacionController.java
esta ok de usar el otro dto pero deberiamos mantener el mapeo para evitar null pointer exceptions

2023-10-12 06:05 UTC, nachogg18 commented on src/main/java/com/bibliotech/controller/EdicionController.java
> -    @GetMapping(path = "/")
yo le sacaria la palabra path, se sobreentiende que si pasas un espacio o una barra es el path

2023-10-12 21:43 UTC, juanrojas216 commented
añadido Objects.nonNull()

2023-10-19 00:30 UTC, nachogg18 approved these changes

2023-10-19 00:30 UTC, merged